# Generated by Django 5.2.7 on 2025-10-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0004_parent_student_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='special_needs',
            new_name='special_needs_description',
        ),
        migrations.AddField(
            model_name='student',
            name='has_special_needs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
