# Generated by Django 4.2.25 on 2025-10-24 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0005_rename_special_needs_student_special_needs_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='special_needs_description',
            new_name='special_needs',
        ),
        migrations.RemoveField(
            model_name='student',
            name='has_special_needs',
        ),
    ]
