# Generated by Django 4.2.25 on 2025-10-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0006_auto_20251024_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
