# Generated by Django 4.2.25 on 2025-10-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0007_alter_student_admission_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('Pre-K', 'Pre-Kindergarten (3-4 years)'), ('K', 'Kindergarten (4-5 years)'), ('Toddler', 'Toddler (2-3 years)'), ('Infant', 'Infant (0-2 years)')], max_length=10),
        ),
    ]
