# Generated by Django 4.2.25 on 2025-10-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0008_alter_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('Playgroup', 'Playgroup / Pre-Nursery'), ('Nursery', 'Nursery'), ('PP1', 'Pre-Primary 1 (KG1)'), ('PP2', 'Pre-Primary 2 (KG2)')], max_length=10),
        ),
    ]
